# Generated by Django 4.2.3 on 2023-09-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.character', verbose_name='Main')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.team', verbose_name='Team')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.franchise'),
        ),
    ]
