# Generated by Django 4.2.3 on 2023-09-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(upload_to='icons/character/'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='icon',
            field=models.ImageField(upload_to='icons/franchise/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='icons/logo/'),
        ),
    ]
