# Generated by Django 4.2.3 on 2023-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0002_alter_character_icon_alter_franchise_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='', verbose_name='icons/flags/'),
        ),
    ]
