# Generated by Django 4.2.3 on 2023-09-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0003_alter_country_flag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Sponsor',
        ),
    ]
