# Generated by Django 4.2.3 on 2023-09-24 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0004_rename_team_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.country'),
        ),
    ]
