# Generated by Django 4.2.3 on 2023-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0005_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='icons/flags'),
        ),
    ]
