# Generated by Django 4.2.3 on 2023-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0006_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='icons'),
        ),
    ]
