# Generated by Django 4.2.3 on 2023-09-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0007_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='icon',
            field=models.ImageField(upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='icons'),
        ),
    ]
