# Generated by Django 4.2.3 on 2023-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0008_alter_character_icon_alter_franchise_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(upload_to='icons/character/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='icons/country/'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='icon',
            field=models.ImageField(upload_to='icons/franchise/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='icons/logo/'),
        ),
    ]
