# Generated by Django 4.2.3 on 2023-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0009_alter_character_icon_alter_country_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
