# Generated by Django 4.2.3 on 2023-09-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jakalapp', '0010_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jakalapp.sponsor', verbose_name='Sponsor'),
        ),
    ]
